services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_DATABASE_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
volumes:
  db-data:
    driver: local